/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/base.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/base.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Default_Floor001.geometry} material={materials['Material.023']} position={[0, 3.198, 0]} scale={0.305} />
      <mesh castShadow receiveShadow geometry={nodes.gharniz.geometry} material={materials['Exterier Door']} scale={0.305} />
      <mesh castShadow receiveShadow geometry={nodes.Default_Floor.geometry} material={materials['Material.065']} scale={0.305} />
      <mesh castShadow receiveShadow geometry={nodes['Wood_-_Stained'].geometry} material={materials['windows metal']} position={[-1.458, 0.1, 6.379]} rotation={[0, 0.157, 0]} scale={0.305} />
      <mesh castShadow receiveShadow geometry={nodes['Clad_-_White'].geometry} material={nodes['Clad_-_White'].material} position={[-1.458, 0.1, 6.379]} rotation={[0, 0.157, 0]} scale={0.305} />
      <mesh castShadow receiveShadow geometry={nodes.Glass.geometry} material={materials['windows glass']} position={[0.797, 0, 5.108]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.305} />
      <mesh castShadow receiveShadow geometry={nodes.MineralWool_ALUPROF_Brown.geometry} material={nodes.MineralWool_ALUPROF_Brown.material} position={[-3.365, 0, -7.256]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.305} />
      <mesh castShadow receiveShadow geometry={nodes.Default_Wall.geometry} material={nodes.Default_Wall.material} scale={0.305} />
      <mesh castShadow receiveShadow geometry={nodes.Gypsum_Wall_Board.geometry} material={materials['Material.023']} scale={0.305} />
      <mesh castShadow receiveShadow geometry={nodes['B&B_MAXALTO_3_013'].geometry} material={materials['B&B_MAXALTO_3_tarelka0.001']} position={[-1.352, 1.693, -4.372]} rotation={[Math.PI / 2, 0, 0.436]} scale={0.001} />
      <mesh castShadow receiveShadow geometry={nodes['B&B_MAXALTO_3_014'].geometry} material={materials['B&B_MAXALTO_3_tarelka1.001']} position={[-1.29, 2.027, -4.338]} rotation={[-3.054, 0, 0]} scale={0.001} />
      <mesh castShadow receiveShadow geometry={nodes['B&B_MAXALTO_3_017'].geometry} material={materials['B&B_MAXALTO_3_korpus.001']} position={[-1.082, 1.857, -4.279]} rotation={[0, 1.571, 0]} scale={0.001} />
      <mesh castShadow receiveShadow geometry={nodes['B&B_MAXALTO_3_020'].geometry} material={materials['B&B_MAXALTO_3_korpus.001']} position={[-1.281, 1.857, -4.331]} rotation={[0, 1.571, 0]} scale={0.001} />
      <mesh castShadow receiveShadow geometry={nodes['B&B_MAXALTO_3_094'].geometry} material={materials['B&B_MAXALTO_3_tarelka2.001']} position={[-1.09, 1.999, -4.285]} rotation={[-3.054, 0, 0]} scale={0.001} />
      <mesh castShadow receiveShadow geometry={nodes['B&B_MAXALTO_3_107'].geometry} material={materials['B&B_MAXALTO_3_tarelka0.001']} position={[-1.191, 1.675, -4.336]} rotation={[Math.PI / 2, 0, -Math.PI / 9]} scale={0.001} />
      <mesh castShadow receiveShadow geometry={nodes['B&B_MAXALTO_3_109'].geometry} material={materials['B&B_MAXALTO_3_tarelka0.001']} position={[-1.557, 1.678, -4.328]} rotation={[Math.PI / 2, 0, 0.148]} scale={0.001} />
      <mesh castShadow receiveShadow geometry={nodes['B&B_MAXALTO_3_121'].geometry} material={materials['B&B_MAXALTO_3_tarelka0.001']} position={[-1.709, 1.547, -4.274]} rotation={[Math.PI, -0.463, Math.PI]} scale={0.001} />
      <mesh castShadow receiveShadow geometry={nodes['B&B_MAXALTO_3_123'].geometry} material={materials['B&B_MAXALTO_3_tarelka0.001']} position={[-1.443, 1.727, -4.354]} rotation={[Math.PI / 2, 0, 0.148]} scale={0.001} />
      <mesh castShadow receiveShadow geometry={nodes['B&B_MAXALTO_3_124'].geometry} material={materials['B&B_MAXALTO_3_tarelka0.001']} position={[-1.737, 1.674, -4.354]} rotation={[Math.PI / 2, 0, -0.637]} scale={0.001} />
      <mesh castShadow receiveShadow geometry={nodes['B&B_MAXALTO_3_134'].geometry} material={materials['B&B_MAXALTO_3_tarelka0_dark.001']} position={[-1.21, 1.548, -4.263]} rotation={[0, -0.436, 0]} scale={0.001} />
      <mesh castShadow receiveShadow geometry={nodes['B&B_MAXALTO_3_136'].geometry} material={materials['B&B_MAXALTO_3_tarelka0.001']} position={[-0.65, 1.643, -4.361]} rotation={[0, 0, -0.436]} scale={0.001} />
      <mesh castShadow receiveShadow geometry={nodes['B&B_MAXALTO_3_221'].geometry} material={materials['Material.064']} position={[-0.518, 1.614, -4.271]} rotation={[0, 0, 0.175]} scale={0.001} />
      <mesh castShadow receiveShadow geometry={nodes['B&B_MAXALTO_3_223'].geometry} material={materials['B&B_MAXALTO_3_Material #20037392.001']} position={[-1.048, 1.766, -4.384]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.001} />
      <mesh castShadow receiveShadow geometry={nodes.Cube002.geometry} material={materials['Material.049']} position={[0.99, 1.688, -3.723]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[1.341, 1, 1.153]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube003.geometry} material={materials['Material.051']} position={[0.995, 1.721, -2.821]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-1.389, -2.403, -1.184]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube004.geometry} material={materials['Material.055']} position={[0.99, 1.721, -2.821]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-1.341, -2.37, -1.153]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube005.geometry} material={materials['Material.053']} position={[0.99, 1.721, -1.904]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-1.341, -2.37, -1.153]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube006.geometry} material={materials['Material.054']} position={[0.995, 1.721, -1.904]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-1.389, -2.403, -1.184]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube007.geometry} material={materials['Material.056']} position={[0.995, 1.721, -0.952]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-1.389, -2.403, -1.184]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube008.geometry} material={materials['Material.057']} position={[0.99, 1.721, -0.952]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-1.341, -2.37, -1.153]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube009.geometry} material={nodes.Cube009.material} position={[-0.83, 1.192, -4.347]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.351, 1, 1]} />
      <mesh castShadow receiveShadow geometry={nodes.Object02.geometry} material={materials.wire_214229166} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <group position={[2.75, 1.871, 1.251]} rotation={[-Math.PI, -0.939, 0]} scale={-0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh029.geometry} material={materials['Material.013']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh029_1.geometry} material={materials['AM109_051_BH.003']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh029_2.geometry} material={materials['AM109_051_hrom.003']} />
      </group>
      <group position={[1.919, 1.028, 1.226]} rotation={[-Math.PI, 0, 0]} scale={-0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh030.geometry} material={materials['AM109_051_hrom.003']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh030_1.geometry} material={materials['AM109_051_hrom.003']} />
      </group>
      <group position={[1.497, 1.028, -0.163]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh031.geometry} material={materials.AM109_050_hrom} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh031_1.geometry} material={materials['AM109_051_hrom.003']} />
      </group>
      <group position={[2.374, 1.291, -0.184]} rotation={[0, -1.083, 0]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh032.geometry} material={materials['Material.014']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh032_1.geometry} material={materials.AM109_050_BH} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh032_2.geometry} material={materials['AM109_051_hrom.003']} />
      </group>
      <group position={[3.612, 1.028, -0.174]} rotation={[-Math.PI, 0, 0]} scale={-0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh036.geometry} material={materials['AM109_050_hrom.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh036_1.geometry} material={materials['AM109_051_hrom.004']} />
      </group>
      <group position={[3.66, 1.871, 0.107]} rotation={[-Math.PI, 0.405, 0]} scale={-0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh037.geometry} material={materials['Material.016']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh037_1.geometry} material={materials['AM109_050_BH.003']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh037_2.geometry} material={materials['AM109_051_hrom.005']} />
      </group>
      <group position={[3.637, 1.028, 0.982]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={-0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh038.geometry} material={materials['AM109_050_hrom.003']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh038_1.geometry} material={materials['AM109_051_hrom.005']} />
      </group>
      <group position={[-4.027, 1.291, -4.346]} rotation={[0, 0.487, 0]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh039.geometry} material={materials['Material.017']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh039_1.geometry} material={materials['AM109_050_BH.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh039_2.geometry} material={materials['AM109_051_hrom.006']} />
      </group>
      <group position={[-4.006, 1.028, -3.469]} rotation={[0, 1.571, 0]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh040.geometry} material={materials['AM109_050_hrom.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh040_1.geometry} material={materials['AM109_051_hrom.006']} />
      </group>
      <group position={[-2.818, 1.028, -4.453]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh041.geometry} material={materials.AM109_055_hrom} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh041_1.geometry} material={materials['Exterier Door']} />
      </group>
      <group position={[-3.693, 1.786, -4.429]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh042.geometry} material={materials['Material.013']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh042_1.geometry} material={materials['Exterier Door']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh042_2.geometry} material={materials.AM109_055_glassMilk} />
      </group>
      <group position={[-2.603, 0, 0.86]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh028.geometry} material={materials['Material.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh028_1.geometry} material={materials['Ficus_lyrata_material_2.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh028_2.geometry} material={materials['Material.004']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh028_3.geometry} material={materials['Material.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh028_4.geometry} material={materials['Material.006']} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Lennox_Carpet_02001.geometry} material={materials['Lennox_Carpet_02.001']} position={[-0.311, 0, -2.302]} rotation={[0, -1.571, 0]} scale={0.001} />
      <mesh castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials['Material.047']} position={[0.99, 1.721, -3.723]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-1.341, -2.37, -1.153]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube001.geometry} material={materials['Material.050']} position={[0.995, 1.721, -3.723]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-1.389, -2.403, -1.184]} />
      <group position={[-0.256, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh769.geometry} material={materials['book_white_7.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh769_1.geometry} material={materials['stranici.069']} />
      </group>
      <group position={[-0.229, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh770.geometry} material={materials['book_Gray_4.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh770_1.geometry} material={materials['stranici.070']} />
      </group>
      <group position={[-0.328, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh771.geometry} material={materials['book__13_1.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh771_1.geometry} material={materials['stranici.071']} />
      </group>
      <group position={[-0.307, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh772.geometry} material={materials['book_white_14.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh772_1.geometry} material={materials['stranici.072']} />
      </group>
      <group position={[-0.355, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh773.geometry} material={materials['book_black_10.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh773_1.geometry} material={materials['stranici.073']} />
      </group>
      <group position={[-0.283, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh774.geometry} material={materials['book_white_3.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh774_1.geometry} material={materials['stranici.074']} />
      </group>
      <group position={[-0.385, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh775.geometry} material={materials['book_white_1.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh775_1.geometry} material={materials['stranici.075']} />
      </group>
      <group position={[-0.411, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh776.geometry} material={materials['book__12_1.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh776_1.geometry} material={materials['stranici.076']} />
      </group>
      <group position={[-0.436, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh777.geometry} material={materials['book_white_4.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh777_1.geometry} material={materials['stranici.077']} />
      </group>
      <group position={[-0.457, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh778.geometry} material={materials['book_Gray_4.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh778_1.geometry} material={materials['stranici.070']} />
      </group>
      <group position={[-0.484, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh779.geometry} material={materials['book__14_1.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh779_1.geometry} material={materials['stranici.078']} />
      </group>
      <group position={[-0.514, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh780.geometry} material={materials['book_black_4.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh780_1.geometry} material={materials['stranici.079']} />
      </group>
      <group position={[-0.54, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh781.geometry} material={materials['book_white_8.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh781_1.geometry} material={materials['stranici.080']} />
      </group>
      <group position={[-0.565, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh782.geometry} material={materials['book_white_9.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh782_1.geometry} material={materials['stranici.081']} />
      </group>
      <group position={[-0.586, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh783.geometry} material={materials['book_black_1.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh783_1.geometry} material={materials['stranici.062']} />
      </group>
      <group position={[-0.613, 1.329, -4.348]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh784.geometry} material={materials['book_white_11.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh784_1.geometry} material={materials['stranici.082']} />
      </group>
      <group position={[-1.143, 1.252, -4.337]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh750.geometry} material={materials['book_1_52.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh750_1.geometry} material={materials['stranici.061']} />
      </group>
      <group position={[-1.149, 1.297, -4.337]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh751.geometry} material={materials['book_black_1.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh751_1.geometry} material={materials['stranici.062']} />
      </group>
      <group position={[-1.151, 1.336, -4.337]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh752.geometry} material={materials['book_1_53.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh752_1.geometry} material={materials['stranici.063']} />
      </group>
      <group position={[-1.182, 1.377, -4.337]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh753.geometry} material={materials['book_1_54.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh753_1.geometry} material={materials['stranici.064']} />
      </group>
      <group position={[-1.167, 1.417, -4.337]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh754.geometry} material={materials['book_1_55.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh754_1.geometry} material={materials['stranici.065']} />
      </group>
      <group position={[-1.162, 1.478, -4.337]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh755.geometry} material={materials['book_1_56.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh755_1.geometry} material={materials['stranici.066']} />
      </group>
      <group position={[-1.162, 1.451, -4.337]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh756.geometry} material={materials['book_1_56.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh756_1.geometry} material={materials['stranici.066']} />
      </group>
      <group position={[-1.037, 1.375, -4.314]} rotation={[-Math.PI / 2, -0.262, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh757.geometry} material={materials['book_1_58.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh757_1.geometry} material={materials['stranici.067']} />
      </group>
      <group position={[-0.985, 1.371, -4.314]} rotation={[-Math.PI / 2, -Math.PI / 9, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh758.geometry} material={materials['book_1_59.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh758_1.geometry} material={materials['stranici.068']} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.objBox01.geometry} material={materials.wire_214229166} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <mesh castShadow receiveShadow geometry={nodes.objBox04.geometry} material={materials['20 - Default']} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <group position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh052.geometry} material={materials.wire_008110135} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh052_1.geometry} material={materials['20___Default']} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Object01.geometry} material={materials.wire_214229166} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <mesh castShadow receiveShadow geometry={nodes.objLine01.geometry} material={materials.FDSF} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <mesh castShadow receiveShadow geometry={nodes.objLine02.geometry} material={materials.FDSF} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <mesh castShadow receiveShadow geometry={nodes.objLine03.geometry} material={materials.FDSF} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <mesh castShadow receiveShadow geometry={nodes.objPlane02.geometry} material={materials.FDSF} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <mesh castShadow receiveShadow geometry={nodes.objPlane03.geometry} material={materials.FDSF} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <mesh castShadow receiveShadow geometry={nodes.objPlane04.geometry} material={materials.FDSF} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <mesh castShadow receiveShadow geometry={nodes.objRectangle02.geometry} material={materials.wire_086086086} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <mesh castShadow receiveShadow geometry={nodes.objRectangle03.geometry} material={materials.wire_154154229} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <mesh castShadow receiveShadow geometry={nodes.objVCD_1.geometry} material={materials['21 - Default']} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <mesh castShadow receiveShadow geometry={nodes.objvcd_2.geometry} material={materials['21 - Default']} position={[-3.008, 1.184, -1.161]} rotation={[0, 1.571, 0]} scale={0.025} />
      <group position={[-2.53, 0.007, -3.456]} rotation={[0, -1.571, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh132.geometry} material={materials['Material.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh132_1.geometry} material={materials['Lennox_Pillow_B_02.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh132_2.geometry} material={materials['Lennox_Pillow_C_02.001']} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Lennox_Plaid_02001.geometry} material={materials['Erica_Plaid_02.001']} position={[-0.22, 2.263, -3.055]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.001} />
      <group position={[0.263, 0.337, -2.889]} rotation={[0, -1.571, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh130.geometry} material={materials['Material.003']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh130_1.geometry} material={materials['Legs_Gloss_02.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh130_2.geometry} material={materials['Legs_Matte_02.001']} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.DCSU_Decor_007001.geometry} material={materials['DCSU_Decor_04.001']} position={[-0.747, 0.362, -2.494]} rotation={[-3.111, -1.36, -3.096]} scale={0.001} />
      <mesh castShadow receiveShadow geometry={nodes.DCSU_Decor_008001.geometry} material={materials['DCSU_Decor_02.001']} position={[-0.8, 0.367, -1.911]} rotation={[0, -Math.PI / 2, 0]} scale={0.001} />
      <group position={[-0.863, 0.351, -2.291]} rotation={[0, -1.571, 0]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh061.geometry} material={materials['Verve_CTable_Top_02.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh061_1.geometry} material={materials['Legs_Gloss_02.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh061_2.geometry} material={materials['Legs_Matte_02.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/base.glb')
